sudo: false
language: go
go:
  - tip
  - 1.9
  - 1.8
script: 
  - go get github.com/golang/lint/golint
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/kisom/goutils/... 
  - go test -cover github.com/kisom/goutils/... 
  - go lint github.com/kisom/goutils/... 
notifications:
  email:
    recipients:
      - coder@kyleisom.net
    on_success: change
    on_failure: change
